### PR TITLE
WIP Fix JCasC lifecycle

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by kuisathaverat** [comment]
this removes the exception but does not load the OpenTelemetry configuration and the logs are not sent
Screenshot 2022-06-02 at 19 46 10

The workaround does not work, even though you save the configuration the logs are not shown or sent, and the APM traces neither are sent

**Comment by kuisathaverat** [comment]
It happens also in the kubernetes deployment we have

**Comment by cyrille-leclerc** [comment]
@kuisathaverat can we create a subsequent issue with the new problem you face?

**Comment by kuisathaverat** [comment]
I just realized that APM is not starting for some reason in the demo.

**Comment by kuisathaverat** [comment]
I just retest it again and it works as expected, sorry for the noise, I will bump the Elastic Stack version on the demo

**Pull request merged**
