### PR TITLE
ES client: support disabling SSL verifications

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
image

Fix:

* https://github.com/jenkinsci/opentelemetry-plugin/issues/480

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Note: only disable SSL hostname verification, not yet self signed certs

**Comment by cyrille-leclerc** [comment]
@kuisathaverat should we add this as a comment that disabling SSL verifications will break SNI and will incompatible with services that use SNIs?

**Comment by kuisathaverat** [comment]
>Note: only disable SSL hostname verification, not yet self signed certs

This comment said that disables the SSL hostname verification Checking the Strategy, it said that accept any certificate as valid, I understand self-signed too, isn't it?
https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/conn/ssl/TrustAllStrategy.html

**Comment by cyrille-leclerc** [comment]
Thanks @kuisathaverat , limitation fixed evolving the coe to
```java
                    try {
                        SSLContext sslContext = new SSLContextBuilder().loadTrustMaterial(null, new TrustAllStrategy()).build();
                        httpClientBuilder.setSSLContext(sslContext);
                    } catch (GeneralSecurityException e) {
                        logger.log(Level.WARNING, "IllegalStateException: failure to disable SSL certs verification");
                    }
                    httpClientBuilder.setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE);
```

**Pull request merged**
