### PR TITLE
Stop masking Guava classes (req Jenkins 2.321)

### PR DESCRIPTION
**Pull request by basil**
Bumps the core baseline to 2.321 (2021-11-16), which has updated version of Guava and Guice, which removes the need for `<maskClasses>com.google.common.</maskClasses>`. This simplifies this plugin's build and deployment. Note that 2.321 is a weekly (not LTS) release, so you may want to wait to merge this until the Guava update is available in an LTS release.

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Thanks @basil , it will be a great simplification.

We just bumped  our Jenkins Core requirement to v2.277.1.
We look at the breakdown by Jenkins Core version of the adoption of the Jenkins Otel Plugin to understand when we can bump. We will see when we can bump and simplify the Guava setup.
See https://stats.jenkins.io/pluginversions/opentelemetry.html
2021/11/29
image

**Comment by basil** [comment]
Refreshed for 2.332.1 LTS

**Comment by cyrille-leclerc** [comment]
Thanks @basil  to follow up on this. As 85% of the installations that can upgrade (ie >= v2.277) are older than v2.321, we are going to wait to bump our requirement.

image

**Comment by cyrille-leclerc** [comment]
Shipped in https://github.com/jenkinsci/opentelemetry-plugin/commit/721c762db006e301280cbc53b4fa0beed78c79ef

**Pull request closed without merging**
