### PR TITLE
Enrich pipeline root span attributes with the build cause

### PR DESCRIPTION
**Pull request by v1v**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### What

Enrich the attributes with the build cause. It allows more than one build reason.

### Why

This will help to understand how many builds are categorised as index branching, manually triggered, downstream based or any other reasons.

### Tasks

- [ ] Agree with the attribute names

### Test

Please click on the `Expand to view`, the images are collapsed

#### Manually triggered

<details><summary>Expand to view</summary>
<p>

image

</p>
</details>

#### Parenstream triggered

<details><summary>Expand to view</summary>
<p>

image

</p>
</details>

#### Timer based

<details><summary>Expand to view</summary>
<p>

image

</p>
</details>

#### Branch indexing

<details><summary>Expand to view</summary>
<p>

image

</p>
</details>

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Very interesting. Can you explain why you have chosen to name your attributes `...cause.name` and `...cause.value`?
I remember us doing it for `ci.pipeline.parameter.name` and `ci.pipeline.parameter.value` but I don't catch how the `.name`/ `.value`pair works for causes. 
I would have expected a multivalued list of the parent job names or the login that triggered the job...

When I see
```
            run.getCauses().stream()
                .forEach( cause -> {
                    causeValues.add(((Cause)cause).getShortDescription());
                    causeNames.add(((Cause)cause).getClass().getSimpleName());
            });
```
It makes me think of `cause.description` and `cause.type` and I don't see something like `cause.pipeline_name`.

I see the challenge with the multiple types of causes.

**Comment by v1v** [comment]
> Maybe the following use cases:

Thats Already in the description od this PR, they are collapsed . Though those screenshots used the previous attribute names.  I'll update them anyway

Or do you mean in the README.md?

> If a pipeline triggers a downstream pipeline, do we see them in one unique trace or is there a disconnect with 2 distinct traces?

aha, gotcha! It is disconnected and we tracked in https://github.com/jenkinsci/opentelemetry-plugin/discussions/98

We could potentially do in a follow up, as we need to figure out how to support `build(wait:false...)`

**Comment by cyrille-leclerc** [comment]
@v1v I didn't see your screenshots in the description.

Some ideas that came to my mind
* The attributes describing the cause (`ci.pipeline.run.cause.*`) should be multivalued to capture the chain of causes up to the root cause (e.g. Git push triggers a job that trigger a downstream job)
* The `ci.pipeline.run.cause.*` attributes could be:
   * `ci.pipeline.run.cause.description`: list of human readable description of build causes
   * `ci.pipeline.run.cause.xxx` (name to be fined): list of machine readable cause like 
      * `UserIdCause:cyrille-leclerc`, 
      * `UpstreamCause:checkout-protobuff#23`, 
      * `GitHubPushCause:cyrille-leclerc`
      * ...

Examples:

| Description | `ci.pipeline.run.cause.description` | `ci.pipeline.run.cause.xxx`
| ------------- | ------------- | ------------- |
| Manually triggered  | ["Started by user Cyrille Le Clerc"] | ["UserIdCause:cyrille-leclerc"] |
| Timer based trigger  | ["Started by timer"] | ["TimerTrigger"] |
| Triggered by GitHub push  | ["Started by GitHub push by cyrille-leclerc"] | ["GitHubPushCause:cyrille-leclerc"] |
| Triggered by parent job triggered by GitHub push  | ["Started by upstream project 'checkout-protobuff' build number 23", "Started by GitHub push by cyrille-leclerc"] | ["UpstreamCause:checkout-protobuff#23", "GitHubPushCause:cyrille-leclerc"] |

**Comment by v1v** [comment]
> Some ideas that came to my mind

See https://github.com/jenkinsci/opentelemetry-plugin/pull/187/commits/f5051d5a5469e2be57fc36cd072f020dcb39cd83 
I also updated the images in the description to reflect the latest changes

Please bear in mind, I used `Xxx` attribute name for the time being, until we agree the name.

**Pull request merged**
